### ISSUE TITLE
Add new hash method crc32c

### ISSUE THREAD

**Issue by 4eUeP** [TeofilC/digest#17]
Hi, what do you think about adding a new hash method `crc32c`? Binding to https://github.com/google/crc32c seems a not bad idea. If you'd be happy to accept a pull request for this, I'll open one later.

**Comment by TeofilC** [comment]
Hi @4eUeP. Thanks for your message!

Adding bindings to that algorithm sounds like a good idea, but I'm a bit worried about adding a dependency on a new C library, since that might make things more complicated for existing users.

Maybe you'd be interested in creating a new package that binds to `google/crc32c`?

**Comment by 4eUeP** [comment]
@TeofilC, thanks for your reply. Yes, that's also what I have worried about. 

However, I can add `google/crc32c` as a submodule and let `cabal` compile it (the `google/crc32c` is also licensed under BSD). So, from the users' point of view, there is nothing more than adding a new module. But it does make the package itself a little more complicated for developers. :thinking:

**Comment by TeofilC** [comment]
Sure that sounds good to me!

**Comment by TeofilC** [comment]
@4eUeP released as  https://hackage.haskell.org/package/digest-0.0.2.0
